export const PHYSICIAN_LOGIN_REQUEST = 'PHYSICIAN_LOGIN_REQUEST'
export const PHYSICIAN_LOGIN_SUCCESS = 'PHYSICIAN_LOGIN_SUCCESS'
export const PHYSICIAN_LOGIN_FAIL = 'PHYSICIAN_LOGIN_FAIL'
export const PHYSICIAN_LOGOUT = 'PHYSICIAN_LOGOUT'
